### PR TITLE
Added "Joypad model" option

### PR DESCRIPTION
**Pull request by Bytezz**
Now it's possible to select a model of Joypad (like DualShock4) to show the appropriate icons.

image

### CODE REVIEW

**Comment by Bytezz** [comment]
PS:
The icons I've used are only for testing purpose, they should be redrawn.

**Comment by KoBeWi** [comment]
That's actually something I wanted to do initially. Godot has some methods to retrieve the joypad model, so this can be detected automatically.
I might implement it a bit differently, but thanks for opening the PR. I'll look into it later.

**Comment by KoBeWi** [comment]
I added the `joypad_model` property in 55a54833b9e0d2c006fb9a52c4788afd859ccb68 and added you as co-author (even though only property name remained from your code 🙃)

I opted for supporting 3 joypad models: Xbox, DualShock, Joy-Con. For DualShock I want with the 4th one, because it's more recognizable as PlayStation controller (symbols have colors). I also added auto-detection and when you set model to auto, it will try to auto-detect when new device is connected.

Thanks for your contribution :)

**Comment by Bytezz** [comment]
> I added the `joypad_model` property in [55a5483](https://github.com/KoBeWi/Godot-Action-Icon/commit/55a54833b9e0d2c006fb9a52c4788afd859ccb68) and added you as co-author (even though only property name remained from your code upside_down_face)
> 
> I opted for supporting 3 joypad models: Xbox, DualShock, Joy-Con. For DualShock I want with the 4th one, because it's more recognizable as PlayStation controller (symbols have colors). I also added auto-detection and when you set model to auto, it will try to auto-detect when new device is connected.
> 
> Thanks for your contribution :)

Really impressive work.
Where did you get those icons? Are they made by you? They are really well made and professional.

**Comment by KoBeWi** [comment]
They are from this free pack https://opengameart.org/content/free-keyboard-and-controllers-prompts-pack
I edited some of them, because e.g. directional sticks were missing.

**Pull request closed without merging**
